project:
  type: website
  output-dir: _build
  render:
    - index.qmd
    - guide/*.qmd
    - api/*.qmd
    - examples/*.qmd
    - about/*.qmd
    - develop/*.qmd
    - develop/*.ipynb
    - contribute/*.qmd
    - blog/**/*.qmd
  resources:
    - api/**
    - _redirects

metadata-files:
  - api/_sidebar.yml

filters:
  - interlinks

interlinks:
 sources:
    python:
      url: https://docs.python.org/3/

website:
  title: "Siuba"
  page-navigation: true
  google-analytics: "G-Y61Q4B2CSD"
  navbar:
    background: light
    search: true
    right:
      - text: "Guide"
        file: guide/overview.qmd
      - text: "Reference"
        href: api/
      - text: "Examples"
        href: examples/index.qmd
        #- text: "Get Involved"
        #  href: contribute/index.qmd
        #- text: "Blog"
        #  href: blog/index.qmd
      - text: "About"
        menu:
          - about/key_features.qmd
          - develop/index.qmd
      - icon: github
        href: https://github.com/machow/siuba/
  sidebar:
    - id: docs
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - guide/overview.qmd
        # - guide/basics-examples.qmd
        - guide/basics-lazy-expressions.qmd
        - guide/basics-sql.qmd
        - section: "Common table verbs"
          contents:
            - guide/verb-filter.qmd
            - guide/verb-arrange.qmd
            - guide/verb-select.qmd
            - guide/verb-mutate.qmd
            - guide/verb-summarize.qmd
            - guide/verb-group-by.qmd
        - section: "Column operations"
          contents:
            - guide/ops-case-when.qmd
            - guide/ops-strings.qmd
            - guide/ops-datetime.qmd
            - guide/ops-categoricals.qmd
            # - guide/ops-autocomplete.qmd
            - guide/ops-support-table.qmd
        - section: "Wrangling"
          contents:
            - guide/wrangle-joins.qmd
            - guide/wrangle-reshape.qmd
            - guide/wrangle-nested.qmd
            - guide/wrangle-helpers.qmd
        - section: "Programming"
          contents:
            - guide/programming-pipes.qmd
            - guide/programming-across.qmd
            # - guide/programming-over.qmd
            - guide/programming-new-verbs.qmd
            - guide/programming-new-ops.qmd
            #- guide/programming-adv-sql.qmd
        - section: "Workflows"
          contents:
            - guide/workflows-backends.qmd
            - guide/workflows.qmd
        - section: "Extra topics"
          contents:
            - guide/extra-r-to-python.qmd
        #    - guide/guide_programming.qmd
    - id: develop
      style: floating
      collapse-level: 2
      align: left
      contents:
        - develop/index.qmd
        - section: "Backends"
          contents:
            - develop/backend_sql.qmd
            - develop/backend_pandas.qmd
        - section: "Core"
          contents:
            - develop/guide_programming.qmd
            - develop/sql-translators.ipynb
            - develop/call_trees.qmd
            - develop/pandas-group-ops.qmd
    - id: dummy

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


quartodoc:
  style: "pkgdown"
  dir: api
  display_name: relative
  package: siuba
  sidebar: api/_sidebar.yml
  renderer:
    style: _renderer.py
    show_signature_annotations: false
  sections:
    - title: "Core verbs - one table"
      desc: ""
      contents:
        - arrange
        - count
        - distinct
        - filter
        - mutate
        # TODO: should be with mutate?
        - transmute
        - rename
        - select
        - summarize
        - group_by
        - ungroup
    - title: "Core verbs - two table"
      desc: ""
      contents:
        # TODO: these should be two entries (mutate joins and filter joins)
        - kind: interlaced
          contents:
            - join
            - name: left_join
            - name: inner_join
            - name: full_join

        - anti_join
        - semi_join
    - title: Query verbs
      desc: Functions that can take a lazy table.
      contents:
        - collect
        - show_query
    - title: "Tidy verbs"
      desc: Functions for tidying table data.
      contents:
        - complete
        - extract
        - gather
        - spread
        - experimental.pivot.pivot_longer
        - experimental.pivot.pivot_wider
        - separate
        - unite
        - nest
        - unnest
    - title: "Column operations"
      desc: ""
      contents:
        - name: dply.vector
          children: flat
        - name: dply.forcats
          children: flat
        - name: experimental.datetime
          members:
            - floor_date
            - ceil_date
          children: flat
