---
title: Verbs and Column Operations
jupyter:
  jupytext:
    formats: 'qmd:quarto'
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.14.0
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---


Table verbs take one or more tables as input, and return a table as output.

```{python}
from siuba import _, count, filter, mutate, select
from siuba.data import mtcars
```

## Syntax


:::{layout-ncol=2}

```{python}
# preferred: pipe data to verb
mtcars >> count(_.cyl)
```


```{python}
#| output: false

# call directly
count(mtcars, _.cyl)
```

:::


## Verbs using tidyselection

Some verbs---like `select()` for keeping specific columns---use a special syntax called tidyselection.
This syntax can be thought of as a mini-language for specifying a set of columns, either
by inclusion or exclusion.

::: {.panel-tabset}

## Siuba

```{python}
#| output: false
# keep cyl column
mtcars >> select(_.cyl)

# keep all *except* cyl column
mtcars >> select(-_.cyl)

# complex select, plus rename cyl to cylinder
mtcars >> select(_.cylinder == _.cyl, _.startswith("m"))
```

## Pandas

```{python}
#| output: false
# keep cyl column
mtcars[["cyl"]]

# keep all *except* cyl column
mtcars.drop(["cyl"], axis=1)

# complex select, plus rename cyl to cylinder
cols = mtcars.columns
mtcars.loc[:, (cols == "cyl") | cols.str.startswith("m")] \
      .rename({"cyl": "cylinder"})
```

:::

More options for tidyselection exist, such as matching patterns, or slicing.
See the [select columns page](./verb-select.qmd) for a discussion of all tidyselect options.



## Pipe to DataFrame methods

Sometimes it is helpful to use Pandas DataFrame methods, in addition to siuba verbs.
This can be done by piping the data to `_.<some_method>()`.

Here is an example using the siuba verb `count()`, with the pandas method `.sort_values()`.
```{python}
(mtcars
    >> count(_.cyl)         # this is a siuba verb
    >> _.sort_values("n")   # this is a pandas method
)
```

Here is another example, using the DataFrame `.shape` attribute.

:::{layout-ncol=2}


```{python}
# siuba pipe
mtcars >> _.shape[0]
```

```{python}
#| output: false
# regular pandas
mtcars.shape[0]
```

:::

## Call external functions

A major advantage of using the pipe approach is that you can pipe any object (e.g. a DataFrame) to any function,
using `call()`.

The example below pipes to the seaborn's `barplot` function.

```{python}
from siuba.siu import call
import seaborn as sns

mtcars >> count(_.cyl) >> call(sns.barplot, x="cyl", y="n", data=_)
```

Note that `sns.barplot()` expects the data as a named argument,
so we pass `data=_`, where `_` is a placeholder for the data.

`call()` can also take a single function to call the data on.

:::{layout-ncol=2}

```{python}
# piping
mtcars >> call(len)
```

```{python}
# regular function call
len(mtcars)
```

:::

## Learning more

* common table verbs section
* custom verbs
* flexible pipes
